spring:
  application:
    name: api-kruger-challenge
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/vaccine-kruger-db
    username: postgres
    password: system
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /api
  error:
    include-stacktrace: never
    path: never